name = "amol-battle-api"
main = "src/index.ts"
compatibility_date = "2026-05-07"

[vars]
FIREBASE_PROJECT_ID = "amol-tracker"

[[kv_namespaces]]
binding = "BATTLE_CODES"
id = "1c46fe73dbbb45be89a0e6a1d61c02b8"
preview_id = "local_dev_only"

[triggers]
crons = ["* * * * *"]
