import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:go_router/go_router.dart';

import '../../../../core/theme/colors.dart';
import '../../../../core/theme/text_styles.dart';
import '../../../battle/models/topic_model.dart';
import '../../repositories/admin_battle_repository.dart';

class AdminBattleTopicFormScreen extends ConsumerStatefulWidget {
  final TopicModel? existingTopic;
  const AdminBattleTopicFormScreen({super.key, this.existingTopic});

  @override
  ConsumerState<AdminBattleTopicFormScreen> createState() => _AdminBattleTopicFormScreenState();
}

class _AdminBattleTopicFormScreenState extends ConsumerState<AdminBattleTopicFormScreen> {
  final _formKey = GlobalKey<FormState>();
  
  late TextEditingController _nameEnController;
  late TextEditingController _nameBnController;
  late TextEditingController _descEnController;
  late TextEditingController _descBnController;
  late TextEditingController _iconController;
  late bool _isActive;
  
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _nameEnController = TextEditingController(text: widget.existingTopic?.nameEn ?? '');
    _nameBnController = TextEditingController(text: widget.existingTopic?.nameBn ?? '');
    _descEnController = TextEditingController(text: widget.existingTopic?.descriptionEn ?? '');
    _descBnController = TextEditingController(text: widget.existingTopic?.descriptionBn ?? '');
    _iconController = TextEditingController(text: widget.existingTopic?.iconName ?? '');
    _isActive = widget.existingTopic?.isActive ?? true;
  }

  @override
  void dispose() {
    _nameEnController.dispose();
    _nameBnController.dispose();
    _descEnController.dispose();
    _descBnController.dispose();
    _iconController.dispose();
    super.dispose();
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;
    
    setState(() => _isLoading = true);
    
    try {
      final repo = ref.read(adminBattleRepositoryProvider);
      
      if (widget.existingTopic == null) {
        final newTopic = TopicModel(
          id: '', // Generated by repo
          nameEn: _nameEnController.text.trim(),
          nameBn: _nameBnController.text.trim(),
          descriptionEn: _descEnController.text.trim(),
          descriptionBn: _descBnController.text.trim(),
          iconName: _iconController.text.trim(),
          isActive: _isActive,
          questionCount: 0,
        );
        await repo.addTopic(newTopic);
      } else {
        final updatedTopic = TopicModel(
          id: widget.existingTopic!.id,
          nameEn: _nameEnController.text.trim(),
          nameBn: _nameBnController.text.trim(),
          descriptionEn: _descEnController.text.trim(),
          descriptionBn: _descBnController.text.trim(),
          iconName: _iconController.text.trim(),
          isActive: _isActive,
          questionCount: widget.existingTopic!.questionCount,
        );
        await repo.updateTopic(updatedTopic);
      }
      
      if (mounted) context.pop();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: AppColors.emeraldDeep,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24.r)),
      ),
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom + 24.h,
        top: 24.h,
        left: 24.w,
        right: 24.w,
      ),
      child: SafeArea(
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              mainAxisSize: MainAxisSize.min,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      widget.existingTopic == null ? 'Create Topic' : 'Edit Topic',
                      style: AppTextStyles.titleLarge(context),
                    ),
                    IconButton(
                      icon: Icon(Icons.close, color: AppColors.textMuted),
                      onPressed: () => context.pop(),
                    ),
                  ],
                ),
                SizedBox(height: 16.h),
                
                TextFormField(
                  controller: _nameEnController,
                  decoration: const InputDecoration(labelText: 'Name (English)'),
                  validator: (v) => v!.isEmpty ? 'Required' : null,
                ),
                SizedBox(height: 12.h),
                
                TextFormField(
                  controller: _nameBnController,
                  decoration: const InputDecoration(labelText: 'Name (Bangla)'),
                  validator: (v) => v!.isEmpty ? 'Required' : null,
                ),
                SizedBox(height: 12.h),
                
                TextFormField(
                  controller: _descEnController,
                  decoration: const InputDecoration(labelText: 'Description (English)'),
                ),
                SizedBox(height: 12.h),
                
                TextFormField(
                  controller: _descBnController,
                  decoration: const InputDecoration(labelText: 'Description (Bangla)'),
                ),
                SizedBox(height: 12.h),
                
                TextFormField(
                  controller: _iconController,
                  decoration: const InputDecoration(labelText: 'Icon URL / Name'),
                ),
                SizedBox(height: 12.h),
                
                SwitchListTile(
                  title: const Text('Is Active'),
                  value: _isActive,
                  activeColor: AppColors.gold,
                  onChanged: (val) => setState(() => _isActive = val),
                  contentPadding: EdgeInsets.zero,
                ),
                SizedBox(height: 24.h),
                
                ElevatedButton(
                  onPressed: _isLoading ? null : _save,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.gold,
                    padding: EdgeInsets.symmetric(vertical: 16.h),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12.r)),
                  ),
                  child: _isLoading
                      ? const CircularProgressIndicator()
                      : Text(
                          'Save Topic',
                          style: TextStyle(color: AppColors.emeraldDeep, fontWeight: FontWeight.bold),
                        ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
