import '../../models/husna_name_model.dart';

/// Asma ul Husna names 1-50.
const List<HusnaName> kAsmaUlHusnaPart1 = <HusnaName>[
  HusnaName(number: 1, arabic: 'ٱلرَّحْمَـٰنُ', transliteration: 'Ar-Rahman', meaning: 'The Most Gracious', meaningBn: 'পরম দয়ালু', benefit: 'Invoke for mercy and ease in hardship.'),
  HusnaName(number: 2, arabic: 'ٱلرَّحِيمُ', transliteration: 'Ar-Rahim', meaning: 'The Most Merciful', meaningBn: 'পরম করুণাময়', benefit: 'Seek forgiveness knowing His mercy surrounds believers.'),
  HusnaName(number: 3, arabic: 'ٱلْمَلِكُ', transliteration: 'Al-Malik', meaning: 'The King', meaningBn: 'মহারাজ', benefit: 'Remember Allah alone owns all authority.'),
  HusnaName(number: 4, arabic: 'ٱلْقُدُّوسُ', transliteration: 'Al-Quddus', meaning: 'The Most Holy', meaningBn: 'পবিত্রতম', benefit: 'Purify intentions before worship and dua.'),
  HusnaName(number: 5, arabic: 'ٱلسَّلَامُ', transliteration: 'As-Salam', meaning: 'The Source of Peace', meaningBn: 'শান্তির উৎস', benefit: 'Turn to Him for inner peace after sin.'),
  HusnaName(number: 6, arabic: 'ٱلْمُؤْمِنُ', transliteration: 'Al-Mu\'min', meaning: 'The Giver of Faith', meaningBn: 'ঈমানদাতা', benefit: 'Ask for steadfast faith in trials.'),
  HusnaName(number: 7, arabic: 'ٱلْمُهَيْمِنُ', transliteration: 'Al-Muhaymin', meaning: 'The Guardian', meaningBn: 'রক্ষক', benefit: 'Trust His watch over every affair.'),
  HusnaName(number: 8, arabic: 'ٱلْعَزِيزُ', transliteration: 'Al-Aziz', meaning: 'The Almighty', meaningBn: 'পরাক্রমশালী', benefit: 'Rely on His power when you feel weak.'),
  HusnaName(number: 9, arabic: 'ٱلْجَبَّارُ', transliteration: 'Al-Jabbar', meaning: 'The Compeller', meaningBn: 'মহাপ্রতাপশালী', benefit: 'Submit brokenness; He mends hearts.'),
  HusnaName(number: 10, arabic: 'ٱلْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', meaning: 'The Supreme', meaningBn: 'মহান', benefit: 'Humble pride before His greatness.'),
  HusnaName(number: 11, arabic: 'ٱلْخَالِقُ', transliteration: 'Al-Khaliq', meaning: 'The Creator', meaningBn: 'স্রষ্টা', benefit: 'Reflect on creation to grow gratitude.'),
  HusnaName(number: 12, arabic: 'ٱلْبَارِئُ', transliteration: 'Al-Bari', meaning: 'The Evolver', meaningBn: 'উদ্ভাবক', benefit: 'See purpose in how He shapes your life.'),
  HusnaName(number: 13, arabic: 'ٱلْمُصَوِّرُ', transliteration: 'Al-Musawwir', meaning: 'The Fashioner', meaningBn: 'আকারদাতা', benefit: 'Accept your form as His wise design.'),
  HusnaName(number: 14, arabic: 'ٱلْغَفَّارُ', transliteration: 'Al-Ghaffar', meaning: 'The Repeatedly Forgiving', meaningBn: 'বারবার ক্ষমাশীল', benefit: 'Never despair of forgiveness after repentance.'),
  HusnaName(number: 15, arabic: 'ٱلْقَهَّارُ', transliteration: 'Al-Qahhar', meaning: 'The Subduer', meaningBn: 'পরাভূতকারী', benefit: 'Let His decree quiet anxious control.'),
  HusnaName(number: 16, arabic: 'ٱلْوَهَّابُ', transliteration: 'Al-Wahhab', meaning: 'The Bestower', meaningBn: 'দানশীল', benefit: 'Ask generously; He gives without measure.'),
  HusnaName(number: 17, arabic: 'ٱلرَّزَّاقُ', transliteration: 'Ar-Razzaq', meaning: 'The Provider', meaningBn: 'রিজিকদাতা', benefit: 'Work with trust that provision is from Him.'),
  HusnaName(number: 18, arabic: 'ٱلْفَتَّاحُ', transliteration: 'Al-Fattah', meaning: 'The Opener', meaningBn: 'উন্মোচনকারী', benefit: 'Call on Him when doors feel closed.'),
  HusnaName(number: 19, arabic: 'ٱلْعَلِيمُ', transliteration: 'Al-Alim', meaning: 'The All-Knowing', meaningBn: 'সর্বজ্ঞ', benefit: 'Speak truth; nothing is hidden from Him.'),
  HusnaName(number: 20, arabic: 'ٱلْقَابِضُ', transliteration: 'Al-Qabid', meaning: 'The Withholder', meaningBn: 'সংকুচিতকারী', benefit: 'Accept restraint as divine wisdom.'),
  HusnaName(number: 21, arabic: 'ٱلْبَاسِطُ', transliteration: 'Al-Basit', meaning: 'The Extender', meaningBn: 'প্রসারক', benefit: 'Hope in expansion after difficulty.'),
  HusnaName(number: 22, arabic: 'ٱلْخَافِضُ', transliteration: 'Al-Khafid', meaning: 'The Reducer', meaningBn: 'নিম্নকারী', benefit: 'Stay humble when honored.'),
  HusnaName(number: 23, arabic: 'ٱلرَّافِعُ', transliteration: 'Ar-Rafi', meaning: 'The Exalter', meaningBn: 'উন্নতকারী', benefit: 'Seek honor through obedience, not ego.'),
  HusnaName(number: 24, arabic: 'ٱلْمُعِزُّ', transliteration: 'Al-Mu\'izz', meaning: 'The Honourer', meaningBn: 'সম্মানদাতা', benefit: 'Ask dignity rooted in taqwa.'),
  HusnaName(number: 25, arabic: 'ٱلْمُذِلُّ', transliteration: 'Al-Mudhill', meaning: 'The Humiliator', meaningBn: 'অপমানকারী', benefit: 'Fear arrogance that leads to disgrace.'),
  HusnaName(number: 26, arabic: 'ٱلسَّمِيعُ', transliteration: 'As-Sami', meaning: 'The All-Hearing', meaningBn: 'সর্বশ্রোতা', benefit: 'Whisper dua with certainty He hears.'),
  HusnaName(number: 27, arabic: 'ٱلْبَصِيرُ', transliteration: 'Al-Basir', meaning: 'The All-Seeing', meaningBn: 'সর্বদর্শী', benefit: 'Guard deeds knowing He sees intent.'),
  HusnaName(number: 28, arabic: 'ٱلْحَكَمُ', transliteration: 'Al-Hakam', meaning: 'The Judge', meaningBn: 'বিচারক', benefit: 'Accept His judgment over disputes.'),
  HusnaName(number: 29, arabic: 'ٱلْعَدْلُ', transliteration: 'Al-Adl', meaning: 'The Just', meaningBn: 'ন্যায়পরায়ণ', benefit: 'Practice fairness in every dealing.'),
  HusnaName(number: 30, arabic: 'ٱللَّطِيفُ', transliteration: 'Al-Latif', meaning: 'The Subtle', meaningBn: 'সূক্ষ্মদাতা', benefit: 'Notice small blessings in daily life.'),
  HusnaName(number: 31, arabic: 'ٱلْخَبِيرُ', transliteration: 'Al-Khabir', meaning: 'The All-Aware', meaningBn: 'সর্বজ্ঞ', benefit: 'Share worries; He knows your state.'),
  HusnaName(number: 32, arabic: 'ٱلْحَلِيمُ', transliteration: 'Al-Halim', meaning: 'The Forbearing', meaningBn: 'সহনশীল', benefit: 'Respond to harm with patience.'),
  HusnaName(number: 33, arabic: 'ٱلْعَظِيمُ', transliteration: 'Al-Azim', meaning: 'The Magnificent', meaningBn: 'মহিমান্বিত', benefit: 'Magnify Him in dhikr and salah.'),
  HusnaName(number: 34, arabic: 'ٱلْغَفُورُ', transliteration: 'Al-Ghafur', meaning: 'The Forgiving', meaningBn: 'ক্ষমাশীল', benefit: 'Repent quickly after mistakes.'),
  HusnaName(number: 35, arabic: 'ٱلشَّكُورُ', transliteration: 'Ash-Shakur', meaning: 'The Appreciative', meaningBn: 'কৃতজ্ঞ', benefit: 'Do small good; He multiplies reward.'),
  HusnaName(number: 36, arabic: 'ٱلْعَلِيُّ', transliteration: 'Al-Ali', meaning: 'The Most High', meaningBn: 'সর্বোচ্চ', benefit: 'Lift your heart above worldly noise.'),
  HusnaName(number: 37, arabic: 'ٱلْكَبِيرُ', transliteration: 'Al-Kabir', meaning: 'The Greatest', meaningBn: 'মহান', benefit: 'Never belittle His command.'),
  HusnaName(number: 38, arabic: 'ٱلْحَفِيظُ', transliteration: 'Al-Hafiz', meaning: 'The Preserver', meaningBn: 'রক্ষক', benefit: 'Trust Him to guard faith and family.'),
  HusnaName(number: 39, arabic: 'ٱلْمُقِيتُ', transliteration: 'Al-Muqit', meaning: 'The Nourisher', meaningBn: 'পোষক', benefit: 'Ask sustenance for body and soul.'),
  HusnaName(number: 40, arabic: 'ٱلْحَسِيبُ', transliteration: 'Al-Hasib', meaning: 'The Reckoner', meaningBn: 'হিসাবকারী', benefit: 'Audit deeds knowing accounts are kept.'),
  HusnaName(number: 41, arabic: 'ٱلْجَلِيلُ', transliteration: 'Al-Jalil', meaning: 'The Majestic', meaningBn: 'মহিমান্বিত', benefit: 'Revere Him in speech and action.'),
  HusnaName(number: 42, arabic: 'ٱلْكَرِيمُ', transliteration: 'Al-Karim', meaning: 'The Generous', meaningBn: 'উদার', benefit: 'Give freely as He gives to you.'),
  HusnaName(number: 43, arabic: 'ٱلرَّقِيبُ', transliteration: 'Ar-Raqib', meaning: 'The Watchful', meaningBn: 'পর্যবেক্ষক', benefit: 'Live as if watched by Ar-Raqib.'),
  HusnaName(number: 44, arabic: 'ٱلْمُجِيبُ', transliteration: 'Al-Mujib', meaning: 'The Responsive', meaningBn: 'উত্তরদাতা', benefit: 'Call upon Him with sincere need.'),
  HusnaName(number: 45, arabic: 'ٱلْوَاسِعُ', transliteration: 'Al-Wasi', meaning: 'The All-Encompassing', meaningBn: 'ব্যাপক', benefit: 'Believe His mercy covers every sin repented.'),
  HusnaName(number: 46, arabic: 'ٱلْحَكِيمُ', transliteration: 'Al-Hakim', meaning: 'The Wise', meaningBn: 'প্রজ্ঞাময়', benefit: 'Accept outcomes as wise even if unclear.'),
  HusnaName(number: 47, arabic: 'ٱلْوَدُودُ', transliteration: 'Al-Wadud', meaning: 'The Loving', meaningBn: 'প্রেমময়', benefit: 'Love others for His sake.'),
  HusnaName(number: 48, arabic: 'ٱلْمَجِيدُ', transliteration: 'Al-Majid', meaning: 'The Glorious', meaningBn: 'মহিমান্বিত', benefit: 'Praise Him for endless glory.'),
  HusnaName(number: 49, arabic: 'ٱلْبَاعِثُ', transliteration: 'Al-Ba\'ith', meaning: 'The Resurrector', meaningBn: 'পুনরুত্থানকারী', benefit: 'Prepare for meeting Him after death.'),
  HusnaName(number: 50, arabic: 'ٱلشَّهِيدُ', transliteration: 'Ash-Shahid', meaning: 'The Witness', meaningBn: 'সাক্ষী', benefit: 'Bear witness to truth without fear.'),
];
