import '../../models/husna_name_model.dart';

/// Asma ul Husna names 51-99.
const List<HusnaName> kAsmaUlHusnaPart2 = <HusnaName>[
  HusnaName(number: 51, arabic: 'ٱلْحَقُّ', transliteration: 'Al-Haqq', meaning: 'The Truth', meaningBn: 'সত্য', benefit: 'Align life with His revealed truth.'),
  HusnaName(number: 52, arabic: 'ٱلْوَكِيلُ', transliteration: 'Al-Wakil', meaning: 'The Trustee', meaningBn: 'তত্ত্বাবধায়ক', benefit: 'Delegate affairs and rely on Al-Wakil.'),
  HusnaName(number: 53, arabic: 'ٱلْقَوِيُّ', transliteration: 'Al-Qawiyy', meaning: 'The Strong', meaningBn: 'শক্তিশালী', benefit: 'Draw strength in worship and patience.'),
  HusnaName(number: 54, arabic: 'ٱلْمَتِينُ', transliteration: 'Al-Matin', meaning: 'The Firm', meaningBn: 'দৃঢ়', benefit: 'Stand firm on principles under pressure.'),
  HusnaName(number: 55, arabic: 'ٱلْوَلِيُّ', transliteration: 'Al-Wali', meaning: 'The Protecting Friend', meaningBn: 'অভিভাবক', benefit: 'Seek nearness through obedience.'),
  HusnaName(number: 56, arabic: 'ٱلْحَمِيدُ', transliteration: 'Al-Hamid', meaning: 'The Praiseworthy', meaningBn: 'প্রশংসিত', benefit: 'Fill tongue with hamd throughout the day.'),
  HusnaName(number: 57, arabic: 'ٱلْمُحْصِي', transliteration: 'Al-Muhsi', meaning: 'The Accounter', meaningBn: 'গণনাকারী', benefit: 'Count blessings to increase shukr.'),
  HusnaName(number: 58, arabic: 'ٱلْمُبْدِئُ', transliteration: 'Al-Mubdi', meaning: 'The Originator', meaningBn: 'সূচনাকারী', benefit: 'Trust new beginnings are by His will.'),
  HusnaName(number: 59, arabic: 'ٱلْمُعِيدُ', transliteration: 'Al-Mu\'id', meaning: 'The Restorer', meaningBn: 'পুনরুদ্ধারকারী', benefit: 'Hope in restoration after loss.'),
  HusnaName(number: 60, arabic: 'ٱلْمُحْيِى', transliteration: 'Al-Muhyi', meaning: 'The Giver of Life', meaningBn: 'জীবনদাতা', benefit: 'Value life as His sacred gift.'),
  HusnaName(number: 61, arabic: 'ٱلْمُمِيتُ', transliteration: 'Al-Mumit', meaning: 'The Creator of Death', meaningBn: 'মৃত্যুদাতা', benefit: 'Remember death to prioritize amal.'),
  HusnaName(number: 62, arabic: 'ٱلْحَىُّ', transliteration: 'Al-Hayy', meaning: 'The Ever-Living', meaningBn: 'চিরঞ্জীব', benefit: 'Attach hope to the Ever-Living Lord.'),
  HusnaName(number: 63, arabic: 'ٱلْقَيُّومُ', transliteration: 'Al-Qayyum', meaning: 'The Self-Subsisting', meaningBn: 'স্বয়ংসম্পূর্ণ', benefit: 'Depend on Him who needs none.'),
  HusnaName(number: 64, arabic: 'ٱلْوَاجِدُ', transliteration: 'Al-Wajid', meaning: 'The Finder', meaningBn: 'অন্বেষক', benefit: 'Seek Him and you will find guidance.'),
  HusnaName(number: 65, arabic: 'ٱلْمَاجِدُ', transliteration: 'Al-Majid', meaning: 'The Noble', meaningBn: 'মহান', benefit: 'Honor His name in gatherings.'),
  HusnaName(number: 66, arabic: 'ٱلْوَاحِدُ', transliteration: 'Al-Wahid', meaning: 'The One', meaningBn: 'এক', benefit: 'Direct worship to the One alone.'),
  HusnaName(number: 67, arabic: 'ٱلْأَحَدُ', transliteration: 'Al-Ahad', meaning: 'The Unique', meaningBn: 'অদ্বিতীয়', benefit: 'Recite Surah Al-Ikhlas with presence.'),
  HusnaName(number: 68, arabic: 'ٱلصَّمَدُ', transliteration: 'As-Samad', meaning: 'The Eternal Refuge', meaningBn: 'চিরস্থায়ী', benefit: 'Turn every need to As-Samad.'),
  HusnaName(number: 69, arabic: 'ٱلْقَادِرُ', transliteration: 'Al-Qadir', meaning: 'The Able', meaningBn: 'সক্ষম', benefit: 'Believe He can change any situation.'),
  HusnaName(number: 70, arabic: 'ٱلْمُقْتَدِرُ', transliteration: 'Al-Muqtadir', meaning: 'The Powerful', meaningBn: 'শক্তিমান', benefit: 'Fear His power over tyrants and self.'),
  HusnaName(number: 71, arabic: 'ٱلْمُقَدِّمُ', transliteration: 'Al-Muqaddim', meaning: 'The Expediter', meaningBn: 'অগ্রসারকারী', benefit: 'Accept timely advancement as His gift.'),
  HusnaName(number: 72, arabic: 'ٱلْمُؤَخِّرُ', transliteration: 'Al-Mu\'akhkhir', meaning: 'The Delayer', meaningBn: 'বিলম্বকারী', benefit: 'Patient when plans are postponed.'),
  HusnaName(number: 73, arabic: 'ٱلْأَوَّلُ', transliteration: 'Al-Awwal', meaning: 'The First', meaningBn: 'প্রথম', benefit: 'Begin deeds with His name.'),
  HusnaName(number: 74, arabic: 'ٱلْآخِرُ', transliteration: 'Al-Akhir', meaning: 'The Last', meaningBn: 'শেষ', benefit: 'End days with repentance and dhikr.'),
  HusnaName(number: 75, arabic: 'ٱلظَّاهِرُ', transliteration: 'Az-Zahir', meaning: 'The Manifest', meaningBn: 'প্রকাশ্য', benefit: 'See His signs in creation daily.'),
  HusnaName(number: 76, arabic: 'ٱلْبَاطِنُ', transliteration: 'Al-Batin', meaning: 'The Hidden', meaningBn: 'গুপ্ত', benefit: 'Know hidden wisdom belongs to Him.'),
  HusnaName(number: 77, arabic: 'ٱلْوَالِي', transliteration: 'Al-Wali', meaning: 'The Governor', meaningBn: 'শাসক', benefit: 'Submit governance of affairs to Him.'),
  HusnaName(number: 78, arabic: 'ٱلْمُتَعَالِي', transliteration: 'Al-Muta\'ali', meaning: 'The Most Exalted', meaningBn: 'উচ্চতম', benefit: 'Lower the self before His exaltation.'),
  HusnaName(number: 79, arabic: 'ٱلْبَرُّ', transliteration: 'Al-Barr', meaning: 'The Source of Goodness', meaningBn: 'কল্যাণকারী', benefit: 'Spread goodness as His attribute.'),
  HusnaName(number: 80, arabic: 'ٱلتَّوَّابُ', transliteration: 'At-Tawwab', meaning: 'The Accepter of Repentance', meaningBn: 'তাওবা গ্রহণকারী', benefit: 'Return to Him again and again.'),
  HusnaName(number: 81, arabic: 'ٱلْمُنْتَقِمُ', transliteration: 'Al-Muntaqim', meaning: 'The Avenger', meaningBn: 'প্রতিশোধকারী', benefit: 'Fear wronging others; justice is His.'),
  HusnaName(number: 82, arabic: 'ٱلْعَفُوُّ', transliteration: 'Al-Afuww', meaning: 'The Pardoner', meaningBn: 'ক্ষমাশীল', benefit: 'Ask Al-Afuw on Laylatul Qadr.'),
  HusnaName(number: 83, arabic: 'ٱلرَّءُوفُ', transliteration: 'Ar-Ra\'uf', meaning: 'The Kind', meaningBn: 'দয়ালু', benefit: 'Show gentleness to the vulnerable.'),
  HusnaName(number: 84, arabic: 'مَالِكُ ٱلْمُلْكِ', transliteration: 'Malik-ul-Mulk', meaning: 'Owner of Sovereignty', meaningBn: 'সার্বভৌমিকতার মালিক', benefit: 'Detach heart from worldly dominion.'),
  HusnaName(number: 85, arabic: 'ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ', transliteration: 'Dhul-Jalali wal-Ikram', meaning: 'Lord of Glory and Honour', meaningBn: 'মহিমা ও সম্মানের অধিপতি', benefit: 'Beg honor from Him, not people.'),
  HusnaName(number: 86, arabic: 'ٱلْمُقْسِطُ', transliteration: 'Al-Muqsit', meaning: 'The Equitable', meaningBn: 'ন্যায়পরায়ণ', benefit: 'Be just even against yourself.'),
  HusnaName(number: 87, arabic: 'ٱلْجَامِعُ', transliteration: 'Al-Jami', meaning: 'The Gatherer', meaningBn: 'একত্রকারী', benefit: 'Hope reunion with loved ones by His will.'),
  HusnaName(number: 88, arabic: 'ٱلْغَنِيُّ', transliteration: 'Al-Ghani', meaning: 'The Self-Sufficient', meaningBn: 'অভাবমুক্ত', benefit: 'Give charity from His entrusted wealth.'),
  HusnaName(number: 89, arabic: 'ٱلْمُغْنِي', transliteration: 'Al-Mughni', meaning: 'The Enricher', meaningBn: 'সমৃদ্ধকারী', benefit: 'Ask halal richness of heart and means.'),
  HusnaName(number: 90, arabic: 'ٱلْمَانِعُ', transliteration: 'Al-Mani', meaning: 'The Preventer', meaningBn: 'নিবারক', benefit: 'Accept blocked harm as His protection.'),
  HusnaName(number: 91, arabic: 'ٱلضَّارُّ', transliteration: 'Ad-Darr', meaning: 'The Distresser', meaningBn: 'ক্ষতিকারী', benefit: 'Seek refuge from harm through dua.'),
  HusnaName(number: 92, arabic: 'ٱلنَّافِعُ', transliteration: 'An-Nafi', meaning: 'The Benefactor', meaningBn: 'উপকারকারী', benefit: 'Ask benefit for dunya and akhirah.'),
  HusnaName(number: 93, arabic: 'ٱلنُّورُ', transliteration: 'An-Nur', meaning: 'The Light', meaningBn: 'আলো', benefit: 'Ask light for chest, path, and guidance.'),
  HusnaName(number: 94, arabic: 'ٱلْهَادِي', transliteration: 'Al-Hadi', meaning: 'The Guide', meaningBn: 'পথপ্রদর্শক', benefit: 'Pray for steadfast guidance.'),
  HusnaName(number: 95, arabic: 'ٱلْبَدِيعُ', transliteration: 'Al-Badi', meaning: 'The Incomparable', meaningBn: 'অতুলনীয়', benefit: 'Marvel at His unmatched creation.'),
  HusnaName(number: 96, arabic: 'ٱلْبَاقِي', transliteration: 'Al-Baqi', meaning: 'The Everlasting', meaningBn: 'চিরস্থায়ী', benefit: 'Invest in deeds that outlast this life.'),
  HusnaName(number: 97, arabic: 'ٱلْوَارِثُ', transliteration: 'Al-Warith', meaning: 'The Inheritor', meaningBn: 'উত্তরাধিকারী', benefit: 'Hold dunia lightly; He inherits all.'),
  HusnaName(number: 98, arabic: 'ٱلرَّشِيدُ', transliteration: 'Ar-Rashid', meaning: 'The Guide to the Right Path', meaningBn: 'সঠিক পথের নির্দেশক', benefit: 'Seek counsel then trust His direction.'),
  HusnaName(number: 99, arabic: 'ٱلصَّبُورُ', transliteration: 'As-Sabur', meaning: 'The Patient', meaningBn: 'ধৈর্যশীল', benefit: 'Practice sabr; He is As-Sabur.'),
];
